name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/poltaratskiy/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_WRITE_KEY}}
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --no-restore --configuration Debug src
    - name: Test
      run: dotnet test --no-build --verbosity normal src
    - name: Create package
      run: dotnet pack --configuration Debug src
    - name: Publish Nuget Package
      run: dotnet nuget push src/TaskManagement.Lib.Authorization/bin/Debug/*.nupkg -k {{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/poltaratskiy/index.json
