name: .NET

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

env:
  DIRECTORY: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/poltaratskiy/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_WRITE_KEY }}
    - name: Restore dependencies
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Debug src
    - name: Test
      run: dotnet test --no-build --verbosity normal src
    - name: Create package
      run: dotnet pack --configuration Debug src/TaskManagement.Lib.Authorization
    - name: Publish Nuget Package
      run: dotnet nuget push src/TaskManagement.Lib.Authorization/bin/Debug/*.nupkg
